version: '1.0.{build}'
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - apveyor-config
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - 
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./MicroRuleEngine/MicroRuleEngine.csproj --verbosity m
build_script:
  - cmd: dotnet build ./MicroRuleEngine/MicroRuleEngine.csproj -c Release
after_build:
  # For once the build has completed
test:
  # only assemblies to test
  assemblies:
    - '**\*.Tests.dll'
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off